# Welcome to Jekyll!
#

# Site settings
title: Astronomy Club IITK
description: We do it in the dark 
owner: Astronomy Club IIT Kanpur # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: astronomyclubiitk@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
# url: "https://astronomyclubiitk.github.io"
social:
  twitter: https://twitter.com/astroclubiitk
  github: https://github.com/astronomyclubiitk
  # linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/AstroClubIITK/
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:astronomyclubiitk@gmail.com
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/user/AstronomyClubIITK
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

permalink: /posts/:year/:month/:day/:title/
collections:
  gallery:
    permalink: /gallery/:path
    output: true
  astrophotographs:
    permalink: /astrophotographs/:path
    output: true
  presentations:
    permalink: /presentations/:path
    output: true
  challenges:
    permalink: /challenges/:path
    output: true
  projects:
    permalink: /projects/:path
    output: true
  contacts:
    permalink: /contacts/:path
    output: true
  events:
    permalink: /events/:path
    output: true